#!/usr/bin/env bash
#
# Copies the conformance fixtures from the TOON specification repository into
# the test target. Run this script when the specification gets a new release.
#
#   Scripts/update-fixtures.sh            # use the pinned tag
#   Scripts/update-fixtures.sh v4.2.0     # move to a new tag
#
# The script writes Tests/ToonFormatTests/Fixtures/PROVENANCE.json. Commit the
# result. A test reads that file and compares the version against the
# specification version that the library targets.

set -euo pipefail

readonly SPEC_REPO="https://github.com/toon-format/spec.git"
readonly DEFAULT_REF="v4.1.1"

readonly REF="${1:-$DEFAULT_REF}"
readonly ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly DEST="$ROOT/Tests/ToonFormatTests/Fixtures"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "Cloning $SPEC_REPO at $REF"
git clone --quiet --depth 1 --branch "$REF" "$SPEC_REPO" "$work/spec"

sha="$(git -C "$work/spec" rev-parse HEAD)"
src="$work/spec/tests/fixtures"

if [ ! -d "$src/encode" ] || [ ! -d "$src/decode" ]; then
  echo "error: $REF has no tests/fixtures/encode and tests/fixtures/decode" >&2
  exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST"
cp -R "$src/encode" "$src/decode" "$DEST/"

cat > "$DEST/PROVENANCE.json" <<JSON
{
  "repo": "toon-format/spec",
  "ref": "$REF",
  "sha": "$sha",
  "retrieved": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "source": "tests/fixtures",
  "note": "Generated by Scripts/update-fixtures.sh. Do not edit by hand."
}
JSON

files="$(find "$DEST" -name '*.json' -not -name 'PROVENANCE.json' | wc -l | tr -d ' ')"
echo "Copied $files fixture files to Tests/ToonFormatTests/Fixtures ($REF, ${sha:0:12})"
echo "Run 'git status' to review the change."
